version: '2.1'
services:

  postgres:
    image: postgres:12.4
    command: |
        -c synchronous_commit=off
        -c effective_cache_size=1536MB
        -c maintenance_work_mem=128MB
        -c work_mem=512kB
        -c max_connections=1024
        -c max_worker_processes=2
        -c max_parallel_workers_per_gather=1
        -c max_parallel_workers=2
        -c min_wal_size=1GB
        -c wal_buffers=16MB
        -c effective_io_concurrency=200
        -c checkpoint_completion_target=0.7
        -c random_page_cost=1.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/database/:/etc/postgres/config/
    #- pg_data:/var/lib/postgresql/data
    networks:
      - pg_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 15s
      retries: 3

  #server:
  #  build: .
  #  image: hivemind
  #  command: |
  #      python -m hivemind.api 
  #  container_name: sevrer
  #  restart: always
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    - pg_network

networks:
  pg_network:
    name: pg_network

#volumes:
#  pg_data:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /home/ubuntu/data
